# Server Configuration
PORT=3000
NODE_ENV=production

# Database Configuration
MONGODB_URI=mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/ev-finder?retryWrites=true&w=majority
MONGODB_TEST_URI=mongodb://localhost:27017/ev-finder-test

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-here
JWT_EXPIRES_IN=7d

# Auth0 Configuration (for token verification)
AUTH0_DOMAIN=dev-zrjqxip57a10h8fo.us.auth0.com
AUTH0_AUDIENCE=your-auth0-api-identifier

# CORS Configuration
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:19006,exp://localhost:19000

# CORS Configuration (Frontend URL)
FRONTEND_URL=https://your-frontend-app.netlify.app

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# External APIs (for future use)
GOOGLE_MAPS_API_KEY=your-google-maps-api-key
CHARGING_STATIONS_API_KEY=your-charging-stations-api-key

# API Configuration
API_VERSION=v1 